name: format and lint workflow
on:
  push:

jobs:
  format:
    runs-on: ubuntulatest
    steps:
      - name: format
        run: npm run format
  lint:
    runs-on: ubuntulatest
    steps:
      - name: lint
        run: npm run lint
