name: CI pour Node.js
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu:latest
    steps:
      - name: Extraire le code du dépôt
        uses: actions/checkout@v4
      - name: Confgurer Node.js
        uses: actions/setupnode@v3
        with:
          nodeversion: '22'
      - name: Installer les dépendances
        run: npm install
      - name: Build
        run: npm run build
  lint:
    runs-on: ubuntu:latest
    steps:
      - name: Extraire le code du dépôt
        uses: actions/checkout@v4
      - name: Confgurer Node.js
        uses: actions/setupnode@v3
        with:
          nodeversion: '22'
      - name: Installer les dépendances
        run: npm install
      - name: Format files
        run: npm run format
      - name: Lint files
        run: npm run lint
